spring.application.name=cyfl

# La dirección donde corre tu MySQL y el nombre de tu base de datos (CYFL)
spring.datasource.url=jdbc:mysql://localhost:3306/CYFL?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true

# Tu usuario de MySQL (por defecto suele ser root)
spring.datasource.username=root

# ⚠️ ¡IMPORTANTE! Cambia esto por la contraseña real que le pusiste a tu MySQL local
spring.datasource.password=root

# El motor que traduce los datos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# 'update' hace que Spring adapte las tablas si cambias algo en los modelos de Java
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de VSCodium los comandos SQL reales que se ejecutan por detrás
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect